#!/usr/bin/env python

import sys

if __name__ == "__main__":
    if len(sys.argv) < 3 or not sys.argv[1].isnumeric() or int(sys.argv[1]) < 1:
        print(f"Usage: cat <pgn file> | {sys.argv[0]} <number of games per file> <output file prefix>")
        sys.exit(1)

    games_per_file = int(sys.argv[1])
    output_file_prefix = sys.argv[2]
    split_count = 0
    game_count = 0
    game_f = None

    for line in sys.stdin:
        if line.startswith('[Event "'):
            if game_count >= games_per_file:
                game_count = 0
                if game_f is not None:
                    game_f.close()
                    game_f = None

            if game_f is None:
                filename = f"{output_file_prefix}.{split_count}.pgn"
                game_f = open(filename, "w")
                split_count += 1
                print(f"Writing {filename}")

            game_count += 1

        game_f.write(line)

    if game_f is not None:
        game_f.close()



