name: Build and Test

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker build . --file Dockerfile --tag chesspy:$(date +%s)

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: docker run chesspy bash -c 'python -m unittest tests'
