name: Build and Test

on: push

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker build . -t chesspy && docker run -t chesspy bash -c 'python -m unittest tests'
